name: Build Executable

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  build-and-release:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.6'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install -r VZE/requirements.txt
    - name: Build package
      run: cd VZE && python setup.py build
    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: vze-build
        path: VZE/build
